spring.output.ansi.enabled=ALWAYS
spring.application.name=lokit

server.port=${PORT:8080}

spring.main.lazy-initialization=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.elshoura.lokit=INFO
logging.level.org.springframework.security=INFO
spring.jpa.show-sql=false

# Database - Railway
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#This is intended to make the project suitable for Neon + Koyeb Free
#and prevent it from crashing due to memory problems or the number of connections.

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=300000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false


# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/liquibase/changelog-master.xml

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Tryon
fal.api.key=${FAL_KEY}
fal.tryon.url=https://fal.run/fal-ai/fashn/tryon/v1.6